// Generated by CoffeeScript 1.9.3
var fs, path, readline, rl, w;

fs = require('fs');

readline = require('readline');

path = 'test/fixtures/file.txt';

rl = readline.createInterface({
  input: fs.createReadStream(path, {
    encoding: 'utf8'
  }),
  output: process.stdout,
  terminal: false
});

w = fs.createWriteStream(path, {
  flags: 'a'
});

w.write('write\n');

w.write('write\n');

rl.on('line', function(line) {
  return console.log(line);
});

rl.on('close', function() {
  return fs.writeFileSync(path, 'a\nb\nc\n');
});
