// Generated by CoffeeScript 1.9.3
var jdb, some_data;

jdb = new (require('../'));

some_data = {
  "name": {
    "first": "Yad",
    "last": "Smood"
  },
  "fav_color": "blue",
  "languages": [
    {
      "name": "Chinese",
      "level": 10
    }, {
      "name": "English",
      "level": 8,
      "preferred": true
    }, {
      "name": "Japenese",
      "level": 6
    }
  ],
  "height": 180,
  "weight": 68
};

jdb.init().then(function() {
  var wrong;
  jdb.exec({
    data: some_data,
    command: function(jdb, data) {
      jdb.doc.ys = data;
      return jdb.save('saved');
    },
    callback: function(err, data) {
      return console.log(data);
    }
  });
  jdb.exec(some_data, function(jdb, data) {
    jdb.doc.arr = data.languages.map(function(el) {
      return el.name;
    });
    return jdb.save();
  }).then(function() {
    return console.log('saved');
  });
  wrong = function() {
    return jdb.exec({
      command: function(jdb) {
        jdb.doc.ys = some_data;
        return jdb.save();
      }
    });
  };
  return console.log(jdb.doc.ys.name);
});
