// Generated by CoffeeScript 1.9.3
var kit;

kit = require('nokit');

module.exports = function(task) {
  task('test', 'Basic test', function() {
  });

  task('benchmark', 'Performance benchmark', function() {
    return kit.spawn('coffee', ['./benchmark/basic.coffee']);
  });

  task('build', 'Compile coffee to js', function() {
    kit.log("Compile coffee...");
    return kit.spawn('coffee', ['-cb', 'lib']);
  });

  task('clean', 'Clean js', function() {
    kit.log("Clean js...");
    return kit.remove('lib', {
      filter: '**/*.js'
    });
  });

  task('dev', 'Start test server', function() {
    return kit.monitorApp({
      args: ['./bin/jdb.js'],
      watchList: ['lib/*.coffee', 'bin/jdb.js']
    });
  });
};
